### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by themihai** [tyler-smith/go-bip39#7]

**Comment by GlenDC** [comment]
I think the silence is your answer... :(

**Comment by scottjbarr** [comment]
Looks active to me.

**Comment by tyler-smith** [comment]
I try to manage the issues and pull requests when I have time and prioritize large bug reports and reviewing/testing/merging submitted PRs and . Sorry I did not get to your question sooner.

Currently there is 1 enhancement request with an accompanying PR that I'm trying to finish testing. The other reported issues is a small bug that I will try pulling in the fix for as soon as I have some free time.

If anybody is interested in helping me with some of this caretaking let me know.

**Comment by GlenDC** [comment]
I wouldn’t mind helping out. For now my organisation has a fork of this repo, would love to collaborate with you to help maintain this lib and make all forks (including our own) obsolete.

**Comment by tyler-smith** [comment]
@GlenDC That sounds great to me. Do you have any patches in your fork or is just forked for your own control/stability?

**Comment by GlenDC** [comment]
Merged some stuff in from other forks and updated some more stuff on top of that. Nothing big though. Will make a PR this weekend so we can start with that.
